### PR TITLE
Fix warnings and convert to new log API.

### PR DESCRIPTION
**Pull request by 23Skidoo**
What it says on the tin.

### CODE REVIEW

**Comment by arybczak** [comment]
I suggest using NoImplicitPrelude instead of CPP to suppress redundant import warnings (same way it's done in `log` package).

**Comment by 23Skidoo** [comment]
Done.

**Comment by jonathanjouty** [comment]
Shouldn't you bump package version?
Other than that LGTM.

**Comment by 23Skidoo** [comment]
Sure, I'll upload a new version to Hackage.

**Pull request merged**
